### PR TITLE
enhance code coverage

### PR DESCRIPTION
**Pull request by kuldipsinghrai**
#PATCH#
@rox163 
@vesper2000 
I have added little more meat to the code coverage piece.

### CODE REVIEW

**Comment by kuldipsinghrai** [comment]
When rebased with upstream, i got the conflict in package.json which was simply just the ordering of few packages so I selected ordering of upstream package.json file.

**Comment by kuldipsinghrai** [comment]
opps need to run lint.

**Comment by rox163** [comment]
Cool. 
Run 'npm test' before any PR. Will run the linter and the test cases for you.

**Comment by rox163** [comment]
:+1:

**Pull request merged**
