### PR TITLE
fix indentation #3

### PR DESCRIPTION
**Pull request by kuldipsinghrai**
#FIX#
@dafortin 
@JasonYe007 
@rox163 
@vesper2000 

This hopefully is the last indentation submission to cover all the files in ember-frost-sidebar.

### CODE REVIEW

**Comment by kuldipsinghrai** [comment]
I am not sure about the cause of the this build failure. :(

**Comment by dafortin** [comment]
One of your test is failing. Run ember test on your local and fix your test.

**Comment by kuldipsinghrai** [comment]
ember test is successful here in my local thats why I am not sure whey it is failing.

**Comment by dafortin** [comment]
Try to relaunch your build in travis

**Comment by kuldipsinghrai** [comment]
relaunch of build (triggered via closing and reopening the PR) did fix the build.

**Comment by rox163** [comment]
:+1:

**Pull request merged**
