### PR TITLE
make publish-coverage.sh executable.

### PR DESCRIPTION
**Pull request by kuldipsinghrai**
#Fix#
chmod +x publish-coverage.sh
@vesper2000 
@rox163

### CODE REVIEW

**Comment by kuldipsinghrai** [comment]
"npm test" successful but load breaks...hmmm :(

**Comment by rox163** [comment]
You need to add the #fix# comment to the PR

**Comment by rox163** [comment]
Add the comment .Close the PR and then reopen it. I think that will trigger the rebuild

**Comment by kuldipsinghrai** [comment]
Thanks Roxanne. So nice to spot and highlight the issue so quick.

**Comment by kuldipsinghrai** [comment]
Build was successful and I can see the code coverage working now.

**Comment by vesper2000** [comment]
👍

**Pull request merged**
